### ISSUE TITLE
Build step?

### ISSUE THREAD

**Issue by LeviOP** [destinygg/dgg-place#8]
Would probably be good to have a build step / workflow that took a native resolution image of the pixel art and turned it into the image that is overlayed as the template.

If whoever is making the templates could post the source pixel art and location it shouldn't be too hard to do

**Comment by definitelynobody** [comment]
downscaling would cause weird artifacts and the original image has an incompatible color palette for r/place

**Comment by LeviOP** [comment]
When I say "native resolution" I don't mean mean an original full size image being downscaled, i mean the original pixel art in the 1000x1000 form, not having each pixel downsized to a 3000x3000 image

**Comment by Brugman** [comment]
https://github.com/Brugman/dgg-place-image-tools

**Comment by LeviOP** [comment]
The way that the script works no longer requires the source image be scaled down.

**Comment by Brugman** [comment]
Yup. 😭
